# Generated by Django 4.1.5 on 2023-05-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('Nproducto', 'Nproducto'), ('tipo', 'tipo')], max_length=100),
        ),
    ]
