# Generated by Django 4.1.5 on 2023-05-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('tipo', 'tipo'), ('Nproducto', 'Nproducto')], max_length=100),
        ),
    ]
